[server]
hostname = "0.0.0.0"
port = 8080
min_threads = 1
max_threads = 8

[sonarqube]
url = "http://localhost:9000/"
token = "3c877121f457abb0b9b8d3f57a8aca602b6d78aa"
scrape_interval = "PT1H"

[prometheus]
metrics_path = "/metrics"

[projects]
include = []
exclude = []

[metrics]
include = []
exclude = []
